# Состояния для ConversationHandler
AWAITING_SOURCE_USERNAME = 1
AWAITING_TARGET_FORWARD = 2
AWAITING_CRITERIA = 3
AWAITING_INTERVAL = 4
AWAITING_PROJECT_NAME = 5
AWAITING_VIEWS = 10
AWAITING_REACTIONS = 11
AWAITING_SIGNATURE = 12
AWAITING_POST_INTERVAL = 13
AWAITING_POST_START_TIME = 17
AWAITING_MEDIA_FILTER = 18
AWAITING_REMOVE_TEXT = 19
AWAITING_KEYWORDS = 20

# Состояния для VK цели
AWAITING_VK_TOKEN = 28
AWAITING_VK_GROUP = 29

# Состояния для редактирования источника
AWAITING_EDIT_VIEWS = 24
AWAITING_EDIT_REACTIONS = 25
AWAITING_EDIT_EXCLUDE_PHRASES = 26
AWAITING_EDIT_KEYWORDS = 27

# Админские состояния
AWAITING_TARIFF_SELECT = 21
AWAITING_BROADCAST_MESSAGE = 23

CURRENT_PROJECT_KEY = "current_project_id"